export const CONFIDENCE_THRESHOLDS = {
  AUTO_PROCEED: 0.9,
  NEEDS_REVIEW: 0.7,
} as const;

export const VALIDATION_RULE_CODES = {
  TOTALS_MATCH: "TOTALS_MATCH",
  REQUIRED_FIELDS_PRESENT: "REQUIRED_FIELDS_PRESENT",
  WORKING_DAYS_IN_RANGE: "WORKING_DAYS_IN_RANGE",
  NO_DUPLICATE_EMPLOYEE: "NO_DUPLICATE_EMPLOYEE",
} as const;

export const MAX_WORKING_DAYS_PER_PERIOD = 31;
